### ISSUE TITLE
remove unused files from the root directory

### ISSUE THREAD

**Issue by zoltuz** [vipulsinghal02/txtlsim_buildacell#13]
## Remove:
* MAKEFILE (not used)
* PENDING (outdated)
* txtl_de_init.m (not sure what's the role of this one)
* startup.m (not sure what's the role of this one)

## Keep:
* CHANGELOG (although this has not been kept up to date)

**Comment by vipulsinghal02** [comment]
Removed all except startup. I think that file is useful for initializing the txtlsim toolbox automatically when one opens MATLAB.
