### ISSUE TITLE
units for parameter values in paper

### ISSUE THREAD

**Issue by pramesh-cfh11** [vipulsinghal02/txtlsim_buildacell#16]
Hello, 
Thanks for developing this codebase. What are the units for the parameters enumerated in Table 1 of the manuscript on biorxiv?

**Comment by vipulsinghal02** [comment]
Hi Pradeep, 

The numerical values are log-transformed values, and the scale of the units involved is nM and seconds. So for example pol_F, which by the supplementary info  is the forward rate for the reaction RNAP + DNA <--> RNAP:DNA, will have units 1/(nM*s). A value of 1.5 for pol_F means that its value is exp^(1.5) nM^(-1) s^(-1).

Another example: pol_{Kd}, which is the Kd for this reaction,  will have units (reverse reaction) / (forward reaction), or, (1/s) / (1/(nM*s)) = nM. So a value of 9.5 is exp^(9.5) nM. 

Does this answer your question?

Best, 
Vipul

**Comment by pramesh-cfh11** [comment]
Thanks Vipul,
That really clears things up!
