### ISSUE TITLE
comb through the core folder and find dead code

### ISSUE THREAD

**Issue by zoltuz** [vipulsinghal02/txtlsim_buildacell#7]
**Goal**: clean up the core by finding dead code.

**Action list**: 
1. string search all the function names in the core folder and find the unused one
2. manually check the list of unused ones 
3. run all examples to see if there's an error caused by regression

**Comment by zoltuz** [comment]
## DECIDE what to do with them
* [DECIDE] txtl_plot_gui is unused (Example is given)
* [DECIDE] txtl_runsim_events is unused
* [DECIDE] txtl_runsim_sensitivity is unused
* [DECIDE] txtl_RNA_config is used by txtl_tx_cascade
* [DECIDE] txtl_tx_cascade: what role this file has?
* [DECIDE] txtl_utr_1SNP10UTR1 is unused
* [DECIDE] txtl_utr_rbs: used by txtl_utr_SNP10UTR1. What's the role this of this file?
* [DECIDE] txtl_utr_SNP10UTR1 is unused

## keep as it is
* [OK] findspecies is a core function
* [OK] txtl_translation is a core function
* [OK] txtl_tx_cascade is used by txtl_transcription_RNAcircuits
* [OK] txtl_transcription_RNAcircuits is used by txtl_prom_t7
* [OK] txtl_transcription is a core function
* [OK] txtl_tetramerize is a core function
* [OK] txtl_setup_new_protein_added is used by txtl_runsim 
* [OK] txtl_setup_default_basepair_length is a core function
* [OK] txtl_runsim is a core function
* [OK] txtl_reaction_config is a core function
* [OK] txtl_protein_degradation is a core function
* [OK] txtl_plot is a core function
* [OK] txtl_parsespec is a core function
* [OK] txtl_newtube is a core function
* [OK] txtl_mrna_degradation is a core function
* [OK] txtl_getDefaultPlotDataStruct is a core function (used by txtl_plot)
* [OK] txtl_extract is a core function
* [OK] txtl_enzyme_resource_degradation is a core function
* [OK] txtl_dna_degradation is a core function
* [OK] txtl_dimerize is a core function
* [OK] txtl_component_config is a core function
* [OK] txtl_combine is a core function
* [OK] txtl_buffer is a core function
* [OK] txtl_addspecies
* [OK] txtl_addreaction
* [OK] txtl_add_dna

**Comment by vipulsinghal02** [comment]
I have removed the files marked by [DECIDE]. It is possible that txtl_utr_rbs.m is needed by some example as we clean them up, so we can add that back if needed. Closing this issue.
